// Saty ATR Levels
// Copyright (C) 2022 Saty Mahajan
// Author is not responsible for your trading using this script.
// Data provided in this script is not financial advice.
//
// Special thanks to Gabriel Viana.
// Based on my own ideas and ideas from Ripster, drippy2hard, 
// Adam Sliver, and others.
//
// Features:
// - Trigger clouds for going long/short intraday @ 23.6 fib
// - Target levels including 61.8 fib and +/- 1 ATR (from previous close)
// Configuration:
// - ATR length
// - Trigger Percentage (0 - 1), default is 23.6 fib
// - Put trigger cloud
// - Call trigger cloud
// - +/- Midrange cloud (defaults to 61.8 fib when using default trigger value)
// - +/-1 ATR from previous close white clouds

//@version=4
study("Saty ATR Levels", shorttitle = "Saty ATR Levels", overlay = true)

// Options
atr_length = input(14, "ATR Length")
trigger_percentage = input(0.236, "Trigger Percentage", type=input.float)
use_todays_close = input(false, "Use Today's Close")
cloud_size = input(4, "Cloud Size")
close_cloud_on = input(true, "Close Cloud")
lower_trigger_cloud_on = input(true, "Lower Trigger Cloud")
lower_middle_cloud_on = input(true, "Lower Middle Cloud")
lower_atr_cloud_on = input(true, "Lower ATR Cloud")
upper_trigger_cloud_on = input(true, "Upper Trigger Cloude")
upper_middle_cloud_on = input(true, "Upper Middle Cloud")
upper_atr_cloud_on = input(true, "Upper ATR Cloud")
close_cloud_color = input(color.white, "Close Cloud")
lower_trigger_cloud_color = input(color.yellow, "Lower Trigger Cloud")
lower_middle_cloud_color = input(color.gray, "Lower Middle Cloud")
lower_atr_cloud_color = input(color.white, "Lower ATR Cloud")
upper_trigger_cloud_color = input(color.aqua, "Upper Trigger Cloud")
upper_middle_cloud_color = input(color.gray, "Upper Middle Cloud")
upper_atr_cloud_color = input(color.white, "Upper ATR Cloud")

// Data
day_index = use_todays_close ? 0 : 1
ticker = tickerid(syminfo.prefix, syminfo.ticker, session=session.regular)
previous_close = security(ticker,"D",close[day_index],gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on)
atr = security(ticker,"D",atr(atr_length)[day_index],gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on)
lower_trigger = previous_close - (trigger_percentage * atr)
upper_trigger = previous_close + (trigger_percentage * atr)
lower_atr = previous_close - atr
upper_atr = previous_close + atr
lower_middle = (lower_trigger + lower_atr) / 2
upper_middle = (upper_trigger + upper_atr) / 2

// Plot levels
plot(lower_atr, color = color.new(lower_atr_cloud_color, 50), linewidth = cloud_size)
plot(lower_middle, color = color.new(lower_middle_cloud_color, 50), linewidth = cloud_size)
plot(lower_trigger, color = color.new(lower_trigger_cloud_color, 50), linewidth = cloud_size)
plot(previous_close, color= color.new(close_cloud_color, 50), linewidth = cloud_size)
plot(upper_trigger, color = color.new(upper_trigger_cloud_color, 50), linewidth = cloud_size)
plot(upper_middle, color = color.new(upper_middle_cloud_color, 50), linewidth = cloud_size)
plot(upper_atr, color = color.new(upper_atr_cloud_color, 50), linewidth = cloud_size)
